// cities.js
const usCities = [
  { name: "New York", state: "NY", country: "US" },
  { name: "Los Angeles", state: "CA", country: "US" },
  { name: "Chicago", state: "IL", country: "US" },
  { name: "Houston", state: "TX", country: "US" },
  { name: "Phoenix", state: "AZ", country: "US" },
  { name: "Philadelphia", state: "PA", country: "US" },
  { name: "San Antonio", state: "TX", country: "US" },
  { name: "San Diego", state: "CA", country: "US" },
  { name: "Dallas", state: "TX", country: "US" },
  { name: "San Jose", state: "CA", country: "US" },
  { name: "Austin", state: "TX", country: "US" },
  { name: "Jacksonville", state: "FL", country: "US" },
  { name: "Fort Worth", state: "TX", country: "US" },
  { name: "Columbus", state: "OH", country: "US" },
  { name: "Charlotte", state: "NC", country: "US" },
  { name: "San Francisco", state: "CA", country: "US" },
  { name: "Indianapolis", state: "IN", country: "US" },
  { name: "Seattle", state: "WA", country: "US" },
  { name: "Denver", state: "CO", country: "US" },
  { name: "Washington", state: "DC", country: "US" },
  { name: "Boston", state: "MA", country: "US" },
  { name: "El Paso", state: "TX", country: "US" },
  { name: "Nashville", state: "TN", country: "US" },
  { name: "Detroit", state: "MI", country: "US" },
  { name: "Oklahoma City", state: "OK", country: "US" },
  { name: "Portland", state: "OR", country: "US" },
  { name: "Las Vegas", state: "NV", country: "US" },
  { name: "Memphis", state: "TN", country: "US" },
  { name: "Louisville", state: "KY", country: "US" },
  { name: "Baltimore", state: "MD", country: "US" },
  { name: "Milwaukee", state: "WI", country: "US" },
  { name: "Albuquerque", state: "NM", country: "US" },
  { name: "Tucson", state: "AZ", country: "US" },
  { name: "Fresno", state: "CA", country: "US" },
  { name: "Mesa", state: "AZ", country: "US" },
  { name: "Sacramento", state: "CA", country: "US" },
  { name: "Atlanta", state: "GA", country: "US" },
  { name: "Kansas City", state: "MO", country: "US" },
  { name: "Colorado Springs", state: "CO", country: "US" },
  { name: "Miami", state: "FL", country: "US" },
  { name: "Raleigh", state: "NC", country: "US" },
  { name: "Omaha", state: "NE", country: "US" },
  { name: "Long Beach", state: "CA", country: "US" },
  { name: "Virginia Beach", state: "VA", country: "US" },
  { name: "Oakland", state: "CA", country: "US" },
  { name: "Minneapolis", state: "MN", country: "US" },
  { name: "Tulsa", state: "OK", country: "US" },
  { name: "Arlington", state: "TX", country: "US" },
  { name: "New Orleans", state: "LA", country: "US" },
  { name: "Wichita", state: "KS", country: "US" }
];

export default usCities;
